connect dbaiot/1234
-- Création de la table USER
CREATE TABLE USERS (
    IDUSER NUMBER PRIMARY KEY,
    LASTNAME VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20),
    EMAIL VARCHAR(40) UNIQUE
);

-- Création de la table SERVICE
CREATE TABLE SERVICE (
    IDSERVICE NUMBER PRIMARY KEY,
    NAME VARCHAR(20),
    SERVICETYPE VARCHAR(20)
);

-- Création de la table THING
CREATE TABLE THING (
    MAC CHAR(17) PRIMARY KEY ,
    IDUSER NUMBER REFERENCES USERS(IDUSER) ON DELETE CASCADE,
    THINGTYPE VARCHAR(20),
    PARAM VARCHAR(20)
);

-- Création de la table SUBSCRIBE
CREATE TABLE SUBSCRIBE (
    IDUSER NUMBER REFERENCES USERS(IDUSER) ON DELETE CASCADE,
    IDSERVICE NUMBER REFERENCES SERVICE(IDSERVICE) ON DELETE CASCADE,
    PRIMARY KEY (IDUSER, IDSERVICE)
);
